// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using comp4976_assignment1.Data;

#nullable disable

namespace comp4976_assignment1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "facd6af5-6bb0-44ad-aca5-93cce530c893",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4e4b89a4-f460-414c-a2d6-3874109b3227",
                            Name = "Finance",
                            NormalizedName = "FINANCE"
                        },
                        new
                        {
                            Id = "a9dc9ead-798e-46a6-84af-8c9c612e4701",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "60b9af18-a29f-4379-b3ac-dd547a3ca237",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87f53036-69fe-4c16-aee0-ed5fb0ce0538",
                            Email = "aa@aa.aa",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AA@AA.AA",
                            NormalizedUserName = "AA@AA.AA",
                            PasswordHash = "AQAAAAIAAYagAAAAEO/ME8jtf+BCewB6QmTHcKgw5GmDuVfcxsOllyxuRrgrdSayyd31NqZSIVtw4LG9Cg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c275a9ea-9630-4144-a472-0b8466a5f678",
                            TwoFactorEnabled = false,
                            UserName = "aa@aa.aa"
                        },
                        new
                        {
                            Id = "15e3d01c-8a65-4047-91ff-5b089343f921",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "696c72d7-c2ac-4f5a-b7da-af7b25da36d6",
                            Email = "mm@mm.mm",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MM@MM.MM",
                            NormalizedUserName = "MM@MM.MM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDuQG1kDtdf/ABBsEfANdupZ1pJBGIw833n5zBFNOCVD7CD4Z6qSjobHFBDhouYC0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb34ac43-f0d8-4028-84cf-8701e67d4afb",
                            TwoFactorEnabled = false,
                            UserName = "mm@mm.mm"
                        },
                        new
                        {
                            Id = "2575ce50-bd4d-4ff3-8250-0a540bd51e96",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0c66e3c-a05f-41a5-8837-458fcf1b279c",
                            Email = "ff@ff.ff",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FF@FF.FF",
                            NormalizedUserName = "FF@FF.FF",
                            PasswordHash = "AQAAAAIAAYagAAAAEJRttWg6emWwKwlbJjj0RKkAqrEXFnNU+aSKySqLMbjFQklFqIVppgoIVA1QQQq5fA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "442eebc7-710c-4d21-9b2e-b0ec95a5a3aa",
                            TwoFactorEnabled = false,
                            UserName = "ff@ff.ff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "60b9af18-a29f-4379-b3ac-dd547a3ca237",
                            RoleId = "facd6af5-6bb0-44ad-aca5-93cce530c893"
                        },
                        new
                        {
                            UserId = "15e3d01c-8a65-4047-91ff-5b089343f921",
                            RoleId = "a9dc9ead-798e-46a6-84af-8c9c612e4701"
                        },
                        new
                        {
                            UserId = "2575ce50-bd4d-4ff3-8250-0a540bd51e96",
                            RoleId = "4e4b89a4-f460-414c-a2d6-3874109b3227"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("comp4976_assignment1.Models.ContactList", b =>
                {
                    b.Property<int>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNo");

                    b.ToTable("ContactList", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNo = 1,
                            City = "New York",
                            Country = "USA",
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9417),
                            CreatedBy = "Seed",
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9471),
                            ModifiedBy = "Seed",
                            PostalCode = "V5T 2W8",
                            Street = "123 Main St"
                        },
                        new
                        {
                            AccountNo = 2,
                            City = "Richmond",
                            Country = "Canada",
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9476),
                            CreatedBy = "Seed",
                            Email = "sam@fox.com",
                            FirstName = "Sam",
                            LastName = "Fox",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9478),
                            ModifiedBy = "Seed",
                            PostalCode = "V4F 1M7",
                            Street = "457 Fox Avenue"
                        },
                        new
                        {
                            AccountNo = 3,
                            City = "Delta",
                            Country = "Canada",
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9481),
                            CreatedBy = "Seed",
                            Email = "ann@day.com",
                            FirstName = "Ann",
                            LastName = "Day",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9485),
                            ModifiedBy = "Seed",
                            PostalCode = "V6G 1M6",
                            Street = "231 River Road"
                        });
                });

            modelBuilder.Entity("comp4976_assignment1.Models.Donations", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransId");

                    b.HasIndex("AccountNo");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Donations", (string)null);

                    b.HasData(
                        new
                        {
                            TransId = 1,
                            AccountNo = 1,
                            Amount = 100f,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9959),
                            CreatedBy = "Seed",
                            Date = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9952),
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9961),
                            ModifiedBy = "Seed",
                            Notes = "This is a first donation",
                            PaymentMethodId = 1,
                            TransactionTypeId = 1
                        },
                        new
                        {
                            TransId = 2,
                            AccountNo = 2,
                            Amount = 100f,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9965),
                            CreatedBy = "Seed",
                            Date = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9963),
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9967),
                            ModifiedBy = "Seed",
                            Notes = "This is a second donation",
                            PaymentMethodId = 1,
                            TransactionTypeId = 2
                        },
                        new
                        {
                            TransId = 3,
                            AccountNo = 3,
                            Amount = 100f,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9970),
                            CreatedBy = "Seed",
                            Date = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9969),
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9972),
                            ModifiedBy = "Seed",
                            Notes = "This is a third donation",
                            PaymentMethodId = 1,
                            TransactionTypeId = 3
                        });
                });

            modelBuilder.Entity("comp4976_assignment1.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethod", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9828),
                            CreatedBy = "Seed",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9833),
                            ModifiedBy = "Seed",
                            Name = "Credit Card"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9837),
                            CreatedBy = "Seed",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9838),
                            ModifiedBy = "Seed",
                            Name = "PayPal"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9855),
                            CreatedBy = "Seed",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9856),
                            ModifiedBy = "Seed",
                            Name = "Debit Card"
                        });
                });

            modelBuilder.Entity("comp4976_assignment1.Models.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionTypeId");

                    b.ToTable("TransactionType", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionTypeId = 1,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9892),
                            CreatedBy = "Seed",
                            Description = "Donations made without any special purpose",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9894),
                            ModifiedBy = "Seed",
                            Name = "General Donation"
                        },
                        new
                        {
                            TransactionTypeId = 2,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9897),
                            CreatedBy = "Seed",
                            Description = "Donations made for homeless people",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9913),
                            ModifiedBy = "Seed",
                            Name = "Food for homeless"
                        },
                        new
                        {
                            TransactionTypeId = 3,
                            Created = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9915),
                            CreatedBy = "Seed",
                            Description = "Donations for the purpose of upgrading the gym",
                            Modified = new DateTime(2023, 10, 15, 21, 21, 36, 625, DateTimeKind.Local).AddTicks(9917),
                            ModifiedBy = "Seed",
                            Name = "Repair of Gym"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("comp4976_assignment1.Models.Donations", b =>
                {
                    b.HasOne("comp4976_assignment1.Models.ContactList", "ContactList")
                        .WithMany()
                        .HasForeignKey("AccountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comp4976_assignment1.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comp4976_assignment1.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactList");

                    b.Navigation("PaymentMethod");

                    b.Navigation("TransactionType");
                });
#pragma warning restore 612, 618
        }
    }
}
